source("renv/activate.R")
#####
# This was automatically generated by mortar. Edit at your own risk!
if(!file.exists('./renv.lock')){
  if(interactive()){
    setup_selection <- menu(c('Yes', 'No'),
                            title = '
It looks like you are setting up this project to use renv for the first time. Would you like to `renv::snapshot()` to save your currently loaded packages?')
  } else{
     setup_selection <- 1
  }
  if(setup_selection == 1){
     renv::snapshot()
  }
}
if(!renv::status()$synchronized){
  if(interactive()){
    sync_selection <- menu(c('Yes', 'No'),
                      title = '
This project uses the renv package to manage package history.
Your version project is currently not synchronized to the renv.lock file.
Would you like to synchronize to the renv.lock file?
If not, renv will be deactivated until you restart your R session.')
  } else {
  sync_selection <- 1
  }
  if(sync_selection == 1){
    do.call(renv::restore,list(project = ".", library = NULL, lockfile = NULL, packages = NULL, exclude = NULL, rebuild = FALSE, repos = NULL, clean = FALSE, prompt = TRUE))
  } else{
    message('Your project was not synchronized. Run renv::status() for more information.')
    renv::deactivate()
  }
}
#####
