source("renv/activate.R")
#####
# This code was automatically generated by the mortar package. Edit at your own risk!
if(any(startsWith(x = readLines('./.Rprofile'), prefix = 'source("renv/activate.R")'))){
  if(!file.exists('./renv.lock')){
    if(interactive()){
      setup_selection <- menu(c('Yes', 'No'),
                              title = '
It looks like you are setting up this project to use renv for the first time. Would you like to run `renv::snapshot()` to save your currently loaded packages?')
    } else{
       setup_selection <- 1
    }
    if(setup_selection == 1){
       renv::snapshot()
       message('Snapshot successful. Re-run `renv::snapshot()` in this project any time you want to update the list of packages.')
    }
  }
  if(!renv::status()$synchronized){
    if(interactive()){
      sync_selection <- menu(c('Yes', 'No'),
                        title = '
This project uses the renv package to manage package versions.
Renv creates a project-specific R installation that is isolated from other versions you have installed on your computer.
This means anyone who runs code in this project is using the same R and R package versions, which is necessary for reproducibility.
The renv.lock file contains information on the R and R package versions used in this project.

Your copy of the project is currently not synchronized to the renv.lock file.
Would you like to run `renv::restore()` to synchronize to the renv.lock file?
If yes, R and R packages will be installed into the renv/ folder of this project with no impact to your other R/package installations.
If no, renv will be deactivated until you restart your R session.')
    } else {
    sync_selection <- 1
    }
    if(sync_selection == 1){
      do.call(renv::restore,list(project = ".", library = NULL, lockfile = NULL, packages = NULL, exclude = NULL, rebuild = FALSE, repos = NULL, clean = FALSE, prompt = TRUE))
    } else{
      message('Your project was not synchronized. If this was a mistake, run `renv::activate(); renv::restore()` to reactivate and sync your project.')
      renv::deactivate()
    }
  }
}
#####
