#' Initialize renv in a USGS project
#'
#' @param project chr; The project directory. When NULL (the default), the
#'   current working directory will be used. The R working directory will be
#'   changed to match the requested project directory.
#' @param profile chr; The profile to be activated. See vignette("profiles",
#'   package = "renv") for more information.
#' @param settings list; 	A list of settings to be used with the
#'   newly-initialized project
#' @param bare lgl; Boolean; initialize the project without attempting to
#'   discover and install R package dependencies?
#' @param force lgl; Boolean; force initialization? By default, renv will refuse
#'   to initialize the home directory as a project, to defend against accidental
#'   mis-usages of init().
#' @param repos chr; The R repositories to be used in this project. See
#'   Repositories for more details.
#' @param bioconductor chr; The version of Bioconductor to be used with this
#'   project. Setting this may be appropriate if renv is unable to determine
#'   that your project depends on a package normally available from
#'   Bioconductor. Set this to TRUE to use the default version of Bioconductor
#'   recommended by the BiocManager package.
#' @param load lgl; Boolean; should the project be loaded after it is
#'   initialized?
#' @param restart lgl; Boolean; attempt to restart the R session after
#'   initializing the project? A session restart will be attempted if the
#'   "restart" R option is set by the frontend embedding R.
#' @param restore_args list; arguments to be passed to the renv::restore()
#'   function whenever the project is out of sync with the renv.lock file.
#'
#' @export
renv_init_usgs <-
  function(project = ".",
           profile = NULL,
           settings = NULL,
           bare = TRUE,
           force = FALSE,
           repos = NULL,
           bioconductor = NULL,
           load = TRUE,
           restart = rlang::is_interactive(),
           restore_args = list(project = project,library = NULL,
                               lockfile = NULL,
                               packages = NULL,
                               exclude = NULL,
                               rebuild = FALSE,
                               repos = NULL,
                               clean = FALSE,
                               prompt = rlang::is_interactive())){

    # before running renv::init, create a custom .Rprofile file that will run at
    # the beginning of every R session in this project
    renv_status_text <-
      glue::glue(
        "#####",
        "# This was automatically generated by mortar. Edit at your own risk!",
        paste0("if(!file.exists('",file.path(project,"renv.lock"),"')){{"),
        "  if(interactive()){{",
        "    setup_selection <- menu(c('Yes', 'No'),",
        "                            title = '\nIt looks like you are setting up this project to use renv for the first time. Would you like to `renv::snapshot()` to save your currently loaded packages?')",
        "  }} else{{",
        "     setup_selection <- 1",
        "  }}",
        "  if(setup_selection == 1){{",
        "     renv::snapshot()",
        "  }}",
        "}}",
        "if(!renv::status()$synchronized){{",
        "  if(interactive()){{",
        "    sync_selection <- menu(c('Yes', 'No'),",
        "                      title = '\nThis project uses the renv package to manage package history.",
        "Your version project is currently not synchronized to the renv.lock file.",
        "Would you like to synchronize to the renv.lock file?",
        "If not, renv will be deactivated until you restart your R session.')",
        "  }} else {{",
        "  sync_selection <- 1",
        "  }}",
        "  if(sync_selection == 1){{",
        paste0("    do.call(renv::restore,",deparse1(restore_args),")"),
        "  }} else{{",
        "    message('Your project was not synchronized. Run renv::status() for more information.')",
        "    renv::deactivate()",
        "  }}",
        "}}",
        "#####",
        "",
        .sep = "\n")

    if(!file.exists(file.path(project, ".Rprofile"))){
      cat(" ",file = file.path(project, ".Rprofile"))
    }
    file_edit(file = file.path(project, ".Rprofile"),
              txt = renv_status_text,
              match = 1,
              append = FALSE)

    renv::init(
      project = project,
      profile = profile,
      settings = settings,
      bare = bare,
      force = force,
      repos = repos,
      bioconductor = bioconductor,
      load = load,
      restart = restart
    )

  }
